#!/bin/bash

#$ -q all.q
#$ -V
#$ -cwd
#$ -N psauron_run

source /Storage/progs/miniconda3/etc/profile.d/conda.sh
conda activate psauron_env

# BASE DIRECTORY
BASE_DIR="/Storage/data1/isabella.gallego/MAESTRIA"

# INPUT: CDS fasta
FASTA_FILE="${BASE_DIR}/all_cds_for_psauron.fasta"

# OUTPUT DIRECTORY
OUTPUT_DIR="${BASE_DIR}/psauron_results"
mkdir -p "$OUTPUT_DIR"

# OUTPUT FILE
OUTPUT_FILE="${OUTPUT_DIR}/psauron_scores.csv"

# PSAURON

psauron -i "$FASTA_FILE" -o "$OUTPUT_FILE"  -c -v

echo "PSAURON DONE"
